version: '3.8'
services:
    server:
        build:
            context: './server'
        ports:
            - '4000:4000'
        volumes:
            - './server/src:/app/src:ro'
            - './server/data/audio:/app/data/audio'
            - '/app/node_modules'
        container_name: 'server'
    client:
        build:
            context: './client'
        ports:
            - '5173:5173'
        volumes:
            - './client/src:/app/src:ro'
            - '/app/node_modules'
        stdin_open: true
        tty: true
        container_name: 'client'
